-- PriceCheck AI V10 schema
create extension if not exists pgcrypto;

create table if not exists retailers (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  website text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  canonical_name text not null,
  brand text,
  model text,
  category text not null,
  specs jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists offers (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references products(id) on delete cascade,
  retailer_id uuid not null references retailers(id) on delete cascade,
  url text not null,
  price_zar numeric(12,2) not null check (price_zar >= 0),
  in_stock boolean,
  last_seen_at timestamptz not null default now(),
  unique(product_id, retailer_id)
);

create table if not exists price_history (
  id bigint generated by default as identity primary key,
  offer_id uuid not null references offers(id) on delete cascade,
  price_zar numeric(12,2) not null check (price_zar >= 0),
  recorded_at timestamptz not null default now()
);

create table if not exists alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  product_id uuid not null references products(id) on delete cascade,
  target_price_zar numeric(12,2) not null check (target_price_zar >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists offers_product_idx on offers(product_id);
create index if not exists offers_price_idx on offers(price_zar);
create index if not exists offers_last_seen_idx on offers(last_seen_at);
create index if not exists history_offer_time_idx on price_history(offer_id, recorded_at desc);
create index if not exists alerts_user_active_idx on alerts(user_id, active);

alter table retailers enable row level security;
alter table products enable row level security;
alter table offers enable row level security;
alter table price_history enable row level security;
alter table alerts enable row level security;

drop policy if exists "public read active retailers" on retailers;
create policy "public read active retailers" on retailers for select using (active = true);

drop policy if exists "public read products" on products;
create policy "public read products" on products for select using (true);

drop policy if exists "public read offers" on offers;
create policy "public read offers" on offers for select using (true);

drop policy if exists "public read price history" on price_history;
create policy "public read price history" on price_history for select using (true);

drop policy if exists "users read own alerts" on alerts;
create policy "users read own alerts" on alerts for select using (auth.uid() = user_id);

drop policy if exists "users create own alerts" on alerts;
create policy "users create own alerts" on alerts for insert with check (auth.uid() = user_id);

drop policy if exists "users update own alerts" on alerts;
create policy "users update own alerts" on alerts for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
